---
# handlers file for setup-apache
- name: start service httpd
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"
  tags: start_apache

- name: start apache2 service
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"
  tags: start_apache
