---
- name: to install tree packages in webservers
  hosts: webservers
  become: true

  tasks:
  - name: installing packages in webserver and appserver
    yum:
      name: git
      state: installed
