---
- name: uninstall the httpd a.k.a apache service from webservers
  hosts: webservers
  become: true
  tasks: 
  - name: uninstall apache
    service:
     name: httpd
     state: stopped
    notify: Remove httpd from webservers
  handlers:
  - name: Remove httpd from webservers
    yum:
      name: httpd
      state: removed
