---
# tasks file for setup-apache
- name: install httpd in webservers
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  tags: install_apache
  notify: start service httpd

- name: install apache2 in appservers
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  tags: install_apache
  notify: start apache2 service

- name: copy index.html to /var/www/html path
  copy:
    src: /opt/ansible/index.html
    dest: /var/www/html
    owner: ansadmin
    mode: '777'


